image: ruby:3.2.1

stages:
  - deploy

deploy-job:

  image: didox/ubuntu-ansible
  stage: deploy
  when: manual


  script:
    - cd ansible-docker
    - echo "$CHAVE_PEM_SERVIDOR" | tr -d '\r' > chave.pem
    - chmod 400 chave.pem
    - ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts deploy.yml -u ubuntu --private-key chave.pem
