image: ruby:3.2.1

stages:
  - deploy

deploy-job:

  image: didox/ubuntu-ansible
  stage: deploy
  when: manual

  script:
    - mkdir ansible-deploy
    - cd ansible-deploy
    - echo "$CHAVE_PEM_SERVIDOR" | tr -d '\r' > chave.pem
    - chmod 400 chave.pem
    - echo "$HOSTS" | tr -d '\r' > hosts
    - echo "$DEPLOY_ANSIBLE" | tr -d '\r' > deploy.yml
    - ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i hosts deploy.yml -u ubuntu --private-key chave.pem

