image: ruby:3.2.1

stages:
  - build
  - test-unidade
  - test-comportamento
  - deploy

build-job:
  rules:
    - if: $CI_COMMIT_TAG

  stage: build
  script:
    - bundle install

unit-test-unidade-job:
  rules:
    - if: $CI_COMMIT_TAG

  stage: test-unidade
  script:
    - echo "Running unit tests... This will take about 60 seconds."

unit-test-comportamento-job:
  rules:
    - if: $CI_COMMIT_TAG

  stage: test-comportamento
  script:
    - echo "Running unit tests... This will take about 60 seconds."

deploy-job:
  rules:
    - if: $CI_COMMIT_TAG

  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
