default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  database: <%= ENV["DB"] %>
  host: <%= ENV["HOST"] %>
  username: <%= ENV["USER"] %>
  password: '<%= ENV["PASS"] %>'