- hosts: app-rails
  become: yes
  tasks:
    - name: "Fazer git pull do código"
      shell: |
        cd /root/rails-postgresql
        git checkout .
        git checkout device
        git pull origin device

    - name: Criar database.yml
      shell: |
        cd /root/rails-postgresql/config
        echo "default: &default" > database.yml
        echo "  adapter: postgresql" >> database.yml
        echo "  encoding: unicode" >> database.yml
        echo "  pool: <%= ENV.fetch(\"RAILS_MAX_THREADS\") { 5 } %>" >> database.yml
        echo "" >> database.yml
        echo "production:" >> database.yml
        echo "  <<: *default" >> database.yml
        echo "  database: <%= ENV[\"DB\"] %>" >> database.yml
        echo "  host: <%= ENV[\"HOST\"] %>" >> database.yml
        echo "  username: <%= ENV[\"USER\"] %>" >> database.yml
        echo "  password: 'p$o5^stsgfDSradAes'" >> database.yml

    - name: Criar docker-compose.yml
      shell: |
        cd /root/rails-postgresql
        echo "version: '3.3'" > docker-compose.yml
        echo "" >> docker-compose.yml
        echo "services:" >> docker-compose.yml
        echo "  app:" >> docker-compose.yml
        echo "    build: ." >> docker-compose.yml
        echo "    ports:" >> docker-compose.yml
        echo "      - \"3000:3000\"" >> docker-compose.yml
        echo "    environment:" >> docker-compose.yml
        echo "      DB: ecommerce_postgresql_production" >> docker-compose.yml
        echo "      HOST: rails-app.crbck5ec0oxi.sa-east-1.rds.amazonaws.com" >> docker-compose.yml
        echo "      USER: postgres" >> docker-compose.yml
        echo "      SECRET_KEY_BASE: 8213b4151a0b78f6667f00eb0f2e3932251e667a2cf52a8e5ed956f644aae462c2d00606bb2ff0517aa8bcd1a0dbb80e7cbe6fb4a6e93453260012bf0cb96e1a" >> docker-compose.yml
        echo "      RAILS_MAX_THREADS: 5" >> docker-compose.yml

    - name: "Executando docker-compose build"
      shell: |
        cd /root/rails-postgresql
        docker-compose build

    - name: "Executando docker-compose up"
      shell: |
        cd /root/rails-postgresql
        docker-compose up -d

    - name: "Aguardar a aplicação iniciar"
      pause:
        seconds: 5

